from fastapi import FastAPI, HTTPException
import random

app = FastAPI()

# In-memory quote storage
quotes = [
    {"id": 1, "text": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt", "category": "motivational"},
    {"id": 2, "text": "I'll be back.", "author": "The Terminator", "category": "movies"},
    {"id": 3, "text": "Not all those who wander are lost.", "author": "J.R.R. Tolkien", "category": "books"},
    {"id": 4, "text": "With great power comes great responsibility.", "author": "Spider-Man", "category": "pop culture"},
    {"id": 5, "text": "Do or do not, there is no try.", "author": "Yoda", "category": "movies"},
    {"id": 6, "text": "It is our choices that show what we truly are, far more than our abilities.", "author": "J.K. Rowling", "category": "books"},
    {"id": 7, "text": "In three words I can sum up everything I've learned about life: it goes on.", "author": "Robert Frost", "category": "motivational"},
    {"id": 8, "text": "Here's looking at you, kid.", "author": "Casablanca", "category": "movies"},
    {"id": 9, "text": "To be, or not to be, that is the question.", "author": "William Shakespeare", "category": "literature"},
    {"id": 10, "text": "May the Force be with you.", "author": "Star Wars", "category": "movies"},
    {"id": 11, "text": "You must be the change you wish to see in the world.", "author": "Mahatma Gandhi", "category": "motivational"},
    {"id": 12, "text": "Not everything that is faced can be changed, but nothing can be changed until it is faced.", "author": "James Baldwin", "category": "books"},
    {"id": 13, "text": "The truth will set you free, but first it will piss you off.", "author": "Gloria Steinem", "category": "motivational"},
    {"id": 14, "text": "To infinity and beyond!", "author": "Buzz Lightyear", "category": "pop culture"},
    {"id": 15, "text": "When you know better, you do better.", "author": "Maya Angelou", "category": "motivational"},
    {"id": 16, "text": "I am Groot.", "author": "Groot", "category": "pop culture"},
    {"id": 17, "text": "Life is what happens when you're busy making other plans.", "author": "John Lennon", "category": "motivational"},
    {"id": 18, "text": "I think, therefore I am.", "author": "René Descartes", "category": "philosophy"},
    {"id": 19, "text": "The greatest glory in living lies not in never falling, but in rising every time we fall.", "author": "Nelson Mandela", "category": "motivational"},
    {"id": 20, "text": "You only live once, but if you do it right, once is enough.", "author": "Mae West", "category": "motivational"},
    {"id": 21, "text": "Get busy living or get busy dying.", "author": "Stephen King", "category": "motivational"},
    {"id": 22, "text": "You miss 100% of the shots you don’t take.", "author": "Wayne Gretzky", "category": "motivational"},
    {"id": 23, "text": "The only impossible journey is the one you never begin.", "author": "Tony Robbins", "category": "motivational"},
    {"id": 24, "text": "Life is either a daring adventure or nothing at all.", "author": "Helen Keller", "category": "motivational"},
    {"id": 25, "text": "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", "author": "Ralph Waldo Emerson", "category": "motivational"},
    {"id": 26, "text": "Be yourself; everyone else is already taken.", "author": "Oscar Wilde", "category": "motivational"},
    {"id": 27, "text": "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", "author": "Albert Einstein", "category": "philosophy"},
    {"id": 28, "text": "So many books, so little time.", "author": "Frank Zappa", "category": "books"},
    {"id": 29, "text": "A room without books is like a body without a soul.", "author": "Marcus Tullius Cicero", "category": "books"},
    {"id": 30, "text": "There is no friend as loyal as a book.", "author": "Ernest Hemingway", "category": "books"},
    {"id": 31, "text": "In the end, we will remember not the words of our enemies, but the silence of our friends.", "author": "Martin Luther King Jr.", "category": "motivational"},
    {"id": 32, "text": "The only way to do great work is to love what you do.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 33, "text": "Success is not final, failure is not fatal: It is the courage to continue that counts.", "author": "Winston Churchill", "category": "motivational"},
    {"id": 34, "text": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius", "category": "motivational"},
    {"id": 35, "text": "Be the change that you wish to see in the world.", "author": "Mahatma Gandhi", "category": "motivational"},
    {"id": 36, "text": "The only way to do great work is to love what you do.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 37, "text": "The best revenge is massive success.", "author": "Frank Sinatra", "category": "motivational"},
    {"id": 38, "text": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson", "category": "motivational"},
    {"id": 39, "text": "What you get by achieving your goals is not as important as what you become by achieving your goals.", "author": "Zig Ziglar", "category": "motivational"},
    {"id": 40, "text": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt", "category": "motivational"},
    {"id": 41, "text": "Life is really simple, but we insist on making it complicated.", "author": "Confucius", "category": "motivational"},
    {"id": 42, "text": "Don't count the days, make the days count.", "author": "Muhammad Ali", "category": "motivational"},
    {"id": 43, "text": "An unexamined life is not worth living.", "author": "Socrates", "category": "philosophy"},
    {"id": 44, "text": "The journey of a thousand miles begins with one step.", "author": "Lao Tzu", "category": "motivational"},
    {"id": 45, "text": "Happiness is not something ready made. It comes from your own actions.", "author": "Dalai Lama", "category": "motivational"},
    {"id": 46, "text": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett", "category": "motivational"},
    {"id": 47, "text": "The best way to predict the future is to create it.", "author": "Abraham Lincoln", "category": "motivational"},
    {"id": 48, "text": "You are never too old to set another goal or to dream a new dream.", "author": "C.S. Lewis", "category": "motivational"},
    {"id": 49, "text": "It always seems impossible until it's done.", "author": "Nelson Mandela", "category": "motivational"},
    {"id": 50, "text": "Don't watch the clock; do what it does. Keep going.", "author": "Sam Levenson", "category": "motivational"},
    {"id": 51, "text": "The secret of getting ahead is getting started.", "author": "Mark Twain", "category": "motivational"},
    {"id": 52, "text": "Do what you can, with what you have, where you are.", "author": "Theodore Roosevelt", "category": "motivational"},
    {"id": 53, "text": "It’s not whether you get knocked down, it’s whether you get up.", "author": "Vince Lombardi", "category": "motivational"},
    {"id": 54, "text": "Everything you can imagine is real.", "author": "Pablo Picasso", "category": "motivational"},
    {"id": 55, "text": "Nothing is impossible, the word itself says ‘I’m possible’!", "author": "Audrey Hepburn", "category": "motivational"},
    {"id": 56, "text": "Life isn't about finding yourself. Life is about creating yourself.", "author": "George Bernard Shaw", "category": "motivational"},
    {"id": 57, "text": "I find that the harder I work, the more luck I seem to have.", "author": "Thomas Jefferson", "category": "motivational"},
    {"id": 58, "text": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney", "category": "motivational"},
    {"id": 59, "text": "The best way to predict the future is to create it.", "author": "Peter Drucker", "category": "motivational"},
    {"id": 60, "text": "You don’t have to be great to start, but you have to start to be great.", "author": "Zig Ziglar", "category": "motivational"},
    {"id": 61, "text": "You must be the change you wish to see in the world.", "author": "Mahatma Gandhi", "category": "motivational"},
    {"id": 62, "text": "To live a creative life, we must lose our fear of being wrong.", "author": "Joseph Chilton Pearce", "category": "motivational"},
    {"id": 63, "text": "The only way to achieve the impossible is to believe it is possible.", "author": "Charles Kingsleigh", "category": "motivational"},
    {"id": 64, "text": "The harder you work for something, the greater you’ll feel when you achieve it.", "author": "Anonymous", "category": "motivational"},
    {"id": 65, "text": "Dream big and dare to fail.", "author": "Norman Vaughan", "category": "motivational"},
    {"id": 66, "text": "Success usually comes to those who are too busy to be looking for it.", "author": "Henry David Thoreau", "category": "motivational"},
    {"id": 67, "text": "Opportunities don't happen, you create them.", "author": "Chris Grosser", "category": "motivational"},
    {"id": 68, "text": "I am not a product of my circumstances. I am a product of my decisions.", "author": "Stephen R. Covey", "category": "motivational"},
    {"id": 69, "text": "A winner is a dreamer who never gives up.", "author": "Nelson Mandela", "category": "motivational"},
    {"id": 70, "text": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt", "category": "motivational"},
    {"id": 71, "text": "Don’t wait for opportunity. Create it.", "author": "Anonymous", "category": "motivational"},
    {"id": 72, "text": "If you can dream it, you can do it.", "author": "Walt Disney", "category": "motivational"},
    {"id": 73, "text": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius", "category": "motivational"},
    {"id": 74, "text": "You don't have to be great to start, but you have to start to be great.", "author": "Zig Ziglar", "category": "motivational"},
    {"id": 75, "text": "Success is not in what you have, but who you are.", "author": "Bo Bennett", "category": "motivational"},
    {"id": 76, "text": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett", "category": "motivational"},
    {"id": 77, "text": "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.", "author": "Jimmy Dean", "category": "motivational"},
    {"id": 78, "text": "The only way to achieve the impossible is to believe it is possible.", "author": "Charles Kingsleigh", "category": "motivational"},
    {"id": 79, "text": "Everything you’ve ever wanted is on the other side of fear.", "author": "George Addair", "category": "motivational"},
    {"id": 80, "text": "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", "author": "Christian D. Larson", "category": "motivational"},
    {"id": 81, "text": "You are never too old to set another goal or to dream a new dream.", "author": "C.S. Lewis", "category": "motivational"},
    {"id": 82, "text": "Don’t watch the clock; do what it does. Keep going.", "author": "Sam Levenson", "category": "motivational"},
    {"id": 83, "text": "Everything has beauty, but not everyone sees it.", "author": "Confucius", "category": "motivational"},
    {"id": 84, "text": "You are braver than you believe, stronger than you seem, and smarter than you think.", "author": "A.A. Milne", "category": "motivational"},
    {"id": 85, "text": "Success is the sum of small efforts, repeated day in and day out.", "author": "Robert Collier", "category": "motivational"},
    {"id": 86, "text": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis", "category": "motivational"},
    {"id": 87, "text": "The best way to get started is to quit talking and begin doing.", "author": "Walt Disney", "category": "motivational"},
    {"id": 88, "text": "When you reach the end of your rope, tie a knot in it and hang on.", "author": "Franklin D. Roosevelt", "category": "motivational"},
    {"id": 89, "text": "Do not wait to strike till the iron is hot, but make it hot by striking.", "author": "William Butler Yeats", "category": "motivational"},
    {"id": 90, "text": "Our greatest glory is not in never falling, but in rising every time we fall.", "author": "Confucius", "category": "motivational"},
    {"id": 91, "text": "Hard work beats talent when talent doesn’t work hard.", "author": "Tim Notke", "category": "motivational"},
    {"id": 92, "text": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt", "category": "motivational"},
    {"id": 93, "text": "Do what you love and you’ll never work a day in your life.", "author": "Confucius", "category": "motivational"},
    {"id": 94, "text": "The mind is everything. What you think you become.", "author": "Buddha", "category": "motivational"},
    {"id": 95, "text": "Life is short, and it is up to you to make it sweet.", "author": "Sarah Louise Delany", "category": "motivational"},
    {"id": 96, "text": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt", "category": "motivational"},
    {"id": 97, "text": "Your time is limited, so don’t waste it living someone else’s life.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 98, "text": "You don't have to be perfect to be amazing.", "author": "Unknown", "category": "motivational"},
    {"id": 99, "text": "The best time to plant a tree was 20 years ago. The second best time is now.", "author": "Chinese Proverb", "category": "motivational"},
    {"id": 100, "text": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson", "category": "motivational"},
    {"id": 101, "text": "If you want to achieve greatness stop asking for permission.", "author": "Anonymous", "category": "motivational"},
    {"id": 102, "text": "In the end, we will remember not the words of our enemies, but the silence of our friends.", "author": "Martin Luther King Jr.", "category": "motivational"},
    {"id": 103, "text": "To live a creative life, we must lose our fear of being wrong.", "author": "Joseph Chilton Pearce", "category": "motivational"},
    {"id": 104, "text": "You are never too old to set another goal or to dream a new dream.", "author": "C.S. Lewis", "category": "motivational"},
    {"id": 105, "text": "Success is not in what you have, but who you are.", "author": "Bo Bennett", "category": "motivational"},
    {"id": 106, "text": "Happiness is not something ready made. It comes from your own actions.", "author": "Dalai Lama", "category": "motivational"},
    {"id": 107, "text": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett", "category": "motivational"},
    {"id": 108, "text": "You must be the change you wish to see in the world.", "author": "Mahatma Gandhi", "category": "motivational"},
    {"id": 109, "text": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt", "category": "motivational"},
    {"id": 110, "text": "It always seems impossible until it's done.", "author": "Nelson Mandela", "category": "motivational"},
    {"id": 111, "text": "Your time is limited, so don’t waste it living someone else’s life.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 112, "text": "The only way to do great work is to love what you do.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 113, "text": "Don’t wait. The time will never be just right.", "author": "Napoleon Hill", "category": "motivational"},
    {"id": 114, "text": "Everything you can imagine is real.", "author": "Pablo Picasso", "category": "motivational"},
    {"id": 115, "text": "Life begins at the end of your comfort zone.", "author": "Neale Donald Walsch", "category": "motivational"},
    {"id": 116, "text": "The best way to predict the future is to create it.", "author": "Abraham Lincoln", "category": "motivational"},
    {"id": 117, "text": "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.", "author": "Jimmy Dean", "category": "motivational"},
    {"id": 118, "text": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius", "category": "motivational"},
    {"id": 119, "text": "A year from now you may wish you had started today.", "author": "Karen Lamb", "category": "motivational"},
    {"id": 120, "text": "It’s not whether you get knocked down, it’s whether you get up.", "author": "Vince Lombardi", "category": "motivational"},
    {"id": 121, "text": "You miss 100% of the shots you don’t take.", "author": "Wayne Gretzky", "category": "motivational"},
    {"id": 122, "text": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt", "category": "motivational"},
    {"id": 123, "text": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis", "category": "motivational"},
    {"id": 124, "text": "Success is not in what you have, but who you are.", "author": "Bo Bennett", "category": "motivational"},
    {"id": 125, "text": "It always seems impossible until it's done.", "author": "Nelson Mandela", "category": "motivational"},
    {"id": 126, "text": "Do what you can, with what you have, where you are.", "author": "Theodore Roosevelt", "category": "motivational"},
    {"id": 127, "text": "If you can dream it, you can do it.", "author": "Walt Disney", "category": "motivational"},
    {"id": 128, "text": "You don’t have to be great to start, but you have to start to be great.", "author": "Zig Ziglar", "category": "motivational"},
    {"id": 129, "text": "Do what you love and you’ll never work a day in your life.", "author": "Confucius", "category": "motivational"},
    {"id": 130, "text": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett", "category": "motivational"},
    {"id": 131, "text": "It is never too late to be what you might have been.", "author": "George Eliot", "category": "motivational"},
    {"id": 132, "text": "The only way to achieve the impossible is to believe it is possible.", "author": "Charles Kingsleigh", "category": "motivational"},
    {"id": 133, "text": "The best way to get started is to quit talking and begin doing.", "author": "Walt Disney", "category": "motivational"},
    {"id": 134, "text": "Don’t wait for opportunity. Create it.", "author": "Anonymous", "category": "motivational"},
    {"id": 135, "text": "Your time is limited, so don’t waste it living someone else’s life.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 136, "text": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt", "category": "motivational"},
    {"id": 137, "text": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt", "category": "motivational"},
    {"id": 138, "text": "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", "author": "Unknown", "category": "motivational"},
    {"id": 139, "text": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis", "category": "motivational"},
    {"id": 140, "text": "The mind is everything. What you think you become.", "author": "Buddha", "category": "motivational"},
    {"id": 141, "text": "Success is not final, failure is not fatal: It is the courage to continue that counts.", "author": "Winston Churchill", "category": "motivational"},
    {"id": 142, "text": "Don’t let yesterday take up too much of today.", "author": "Will Rogers", "category": "motivational"},
    {"id": 143, "text": "You are never too old to set another goal or to dream a new dream.", "author": "C.S. Lewis", "category": "motivational"},
    {"id": 144, "text": "There are no limits to what you can accomplish, except the limits you place on your own thinking.", "author": "Brian Tracy", "category": "motivational"},
    {"id": 145, "text": "You don’t have to be perfect to be amazing.", "author": "Unknown", "category": "motivational"},
    {"id": 146, "text": "Success is not the key to happiness. Happiness is the key to success.", "author": "Albert Schweitzer", "category": "motivational"},
    {"id": 147, "text": "What you get by achieving your goals is not as important as what you become by achieving your goals.", "author": "Zig Ziglar", "category": "motivational"},
    {"id": 148, "text": "Don’t stop when you’re tired. Stop when you’re done.", "author": "Anonymous", "category": "motivational"},
    {"id": 149, "text": "Do what you love and you’ll never work a day in your life.", "author": "Confucius", "category": "motivational"},
    {"id": 150, "text": "If you want something you’ve never had, you must be willing to do something you’ve never done.", "author": "Thomas Jefferson", "category": "motivational"},
    {"id": 151, "text": "Don't watch the clock; do what it does. Keep going.", "author": "Sam Levenson", "category": "motivational"},
    {"id": 152, "text": "The harder you work for something, the greater you’ll feel when you achieve it.", "author": "Anonymous", "category": "motivational"},
    {"id": 153, "text": "Great things never come from comfort zones.", "author": "Anonymous", "category": "motivational"},
    {"id": 154, "text": "Dream it. Wish it. Do it.", "author": "Anonymous", "category": "motivational"},
    {"id": 155, "text": "It’s going to be hard, but hard does not mean impossible.", "author": "Anonymous", "category": "motivational"},
    {"id": 156, "text": "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", "author": "Anonymous", "category": "motivational"},
    {"id": 157, "text": "The key to success is to focus on goals, not obstacles.", "author": "Anonymous", "category": "motivational"},
    {"id": 158, "text": "You don’t have to be great to start, but you have to start to be great.", "author": "Zig Ziglar", "category": "motivational"},
    {"id": 159, "text": "It’s not about being the best. It’s about being better than you were yesterday.", "author": "Anonymous", "category": "motivational"},
    {"id": 160, "text": "Start where you are. Use what you have. Do what you can.", "author": "Arthur Ashe", "category": "motivational"},
    {"id": 161, "text": "Be yourself; everyone else is already taken.", "author": "Oscar Wilde", "category": "motivational"},
    {"id": 162, "text": "Success usually comes to those who are too busy to be looking for it.", "author": "Henry David Thoreau", "category": "motivational"},
    {"id": 163, "text": "The best revenge is massive success.", "author": "Frank Sinatra", "category": "motivational"},
    {"id": 164, "text": "Action is the foundational key to all success.", "author": "Pablo Picasso", "category": "motivational"},
    {"id": 165, "text": "I find that the harder I work, the more luck I seem to have.", "author": "Thomas Jefferson", "category": "motivational"},
    {"id": 166, "text": "Don’t be afraid to give up the good to go for the great.", "author": "John D. Rockefeller", "category": "motivational"},
    {"id": 167, "text": "Success is not the key to happiness. Happiness is the key to success.", "author": "Albert Schweitzer", "category": "motivational"},
    {"id": 168, "text": "You only live once, but if you do it right, once is enough.", "author": "Mae West", "category": "motivational"},
    {"id": 169, "text": "It always seems impossible until it’s done.", "author": "Nelson Mandela", "category": "motivational"},
    {"id": 170, "text": "Act as if what you do makes a difference. It does.", "author": "William James", "category": "motivational"},
    {"id": 171, "text": "Success is walking from failure to failure with no loss of enthusiasm.", "author": "Winston Churchill", "category": "motivational"},
    {"id": 172, "text": "I would rather die of passion than of boredom.", "author": "Vincent van Gogh", "category": "motivational"},
    {"id": 173, "text": "Don’t let yesterday take up too much of today.", "author": "Will Rogers", "category": "motivational"},
    {"id": 174, "text": "Don’t limit your challenges. Challenge your limits.", "author": "Anonymous", "category": "motivational"},
    {"id": 175, "text": "If you don’t build your dream, someone else will hire you to help them build theirs.", "author": "Dhirubhai Ambani", "category": "motivational"},
    {"id": 176, "text": "The only impossible journey is the one you never begin.", "author": "Tony Robbins", "category": "motivational"},
    {"id": 177, "text": "Success is not final, failure is not fatal: It is the courage to continue that counts.", "author": "Winston Churchill", "category": "motivational"},
    {"id": 178, "text": "It’s not the years in your life that count. It’s the life in your years.", "author": "Abraham Lincoln", "category": "motivational"},
    {"id": 179, "text": "Success is not the key to happiness. Happiness is the key to success.", "author": "Albert Schweitzer", "category": "motivational"},
    {"id": 180, "text": "The secret of getting ahead is getting started.", "author": "Mark Twain", "category": "motivational"},
    {"id": 181, "text": "The best way to predict your future is to create it.", "author": "Abraham Lincoln", "category": "motivational"},
    {"id": 182, "text": "There are no limits to what you can accomplish, except the limits you place on your own thinking.", "author": "Brian Tracy", "category": "motivational"},
    {"id": 183, "text": "Don’t wait. The time will never be just right.", "author": "Napoleon Hill", "category": "motivational"},
    {"id": 184, "text": "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", "author": "Christian D. Larson", "category": "motivational"},
    {"id": 185, "text": "The only way to do great work is to love what you do.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 186, "text": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt", "category": "motivational"},
    {"id": 187, "text": "It is never too late to be what you might have been.", "author": "George Eliot", "category": "motivational"},
    {"id": 188, "text": "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", "author": "Unknown", "category": "motivational"},
    {"id": 189, "text": "If you want to achieve greatness stop asking for permission.", "author": "Anonymous", "category": "motivational"},
    {"id": 190, "text": "In the end, we will remember not the words of our enemies, but the silence of our friends.", "author": "Martin Luther King Jr.", "category": "motivational"},
    {"id": 191, "text": "To live a creative life, we must lose our fear of being wrong.", "author": "Joseph Chilton Pearce", "category": "motivational"},
    {"id": 192, "text": "You are never too old to set another goal or to dream a new dream.", "author": "C.S. Lewis", "category": "motivational"},
    {"id": 193, "text": "Success is not in what you have, but who you are.", "author": "Bo Bennett", "category": "motivational"},
    {"id": 194, "text": "Happiness is not something ready made. It comes from your own actions.", "author": "Dalai Lama", "category": "motivational"},
    {"id": 195, "text": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett", "category": "motivational"},
    {"id": 196, "text": "You must be the change you wish to see in the world.", "author": "Mahatma Gandhi", "category": "motivational"},
    {"id": 197, "text": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt", "category": "motivational"},
    {"id": 198, "text": "It always seems impossible until it's done.", "author": "Nelson Mandela", "category": "motivational"},
    {"id": 199, "text": "Your time is limited, so don’t waste it living someone else’s life.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 200, "text": "The only way to do great work is to love what you do.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 201, "text": "The future depends on what we do in the present.", "author": "Mahatma Gandhi", "category": "motivational"},
    {"id": 202, "text": "Life is what happens when you’re busy making other plans.", "author": "John Lennon", "category": "motivational"},
    {"id": 203, "text": "If you want to go fast, go alone. If you want to go far, go together.", "author": "African Proverb", "category": "motivational"},
    {"id": 204, "text": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt", "category": "motivational"},
    {"id": 205, "text": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney", "category": "motivational"},
    {"id": 206, "text": "The best time to plant a tree was 20 years ago. The second best time is now.", "author": "Chinese Proverb", "category": "motivational"},
    {"id": 207, "text": "Don’t count the days, make the days count.", "author": "Muhammad Ali", "category": "motivational"},
    {"id": 208, "text": "Everything you can imagine is real.", "author": "Pablo Picasso", "category": "motivational"},
    {"id": 209, "text": "You are braver than you believe, stronger than you seem, and smarter than you think.", "author": "A.A. Milne", "category": "motivational"},
    {"id": 210, "text": "The only place where success comes before work is in the dictionary.", "author": "Vidal Sassoon", "category": "motivational"},
    {"id": 211, "text": "Opportunities don't happen, you create them.", "author": "Chris Grosser", "category": "motivational"},
    {"id": 212, "text": "Everything has beauty, but not everyone sees it.", "author": "Confucius", "category": "motivational"},
    {"id": 213, "text": "Don’t wait for opportunity. Create it.", "author": "Anonymous", "category": "motivational"},
    {"id": 214, "text": "The only way to achieve the impossible is to believe it is possible.", "author": "Charles Kingsleigh", "category": "motivational"},
    {"id": 215, "text": "Your limitation—it's only your imagination.", "author": "Anonymous", "category": "motivational"},
    {"id": 216, "text": "Push yourself, because no one else is going to do it for you.", "author": "Anonymous", "category": "motivational"},
    {"id": 217, "text": "Great things never come from comfort zones.", "author": "Anonymous", "category": "motivational"},
    {"id": 218, "text": "Dream it. Believe it. Build it.", "author": "Anonymous", "category": "motivational"},
    {"id": 219, "text": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt", "category": "motivational"},
    {"id": 220, "text": "The best way to predict the future is to create it.", "author": "Abraham Lincoln", "category": "motivational"},
    {"id": 221, "text": "Nothing is impossible. The word itself says 'I'm possible!'", "author": "Audrey Hepburn", "category": "motivational"},
    {"id": 222, "text": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius", "category": "motivational"},
    {"id": 223, "text": "Don’t stop when you’re tired. Stop when you’re done.", "author": "Anonymous", "category": "motivational"},
    {"id": 224, "text": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis", "category": "motivational"},
    {"id": 225, "text": "We may encounter many defeats, but we must not be defeated.", "author": "Maya Angelou", "category": "motivational"},
    {"id": 226, "text": "The only way to do great work is to love what you do.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 227, "text": "It’s not whether you get knocked down, it’s whether you get up.", "author": "Vince Lombardi", "category": "motivational"},
    {"id": 228, "text": "If you’re going through hell, keep going.", "author": "Winston Churchill", "category": "motivational"},
    {"id": 229, "text": "You miss 100% of the shots you don’t take.", "author": "Wayne Gretzky", "category": "motivational"},
    {"id": 230, "text": "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", "author": "Winston Churchill", "category": "motivational"},
    {"id": 231, "text": "Do what you can, with what you have, where you are.", "author": "Theodore Roosevelt", "category": "motivational"},
    {"id": 232, "text": "In order to succeed, we must first believe that we can.", "author": "Nikos Kazantzakis", "category": "motivational"},
    {"id": 233, "text": "The mind is everything. What you think you become.", "author": "Buddha", "category": "motivational"},
    {"id": 234, "text": "What you get by achieving your goals is not as important as what you become by achieving your goals.", "author": "Zig Ziglar", "category": "motivational"},
    {"id": 235, "text": "Success is not in what you have, but who you are.", "author": "Bo Bennett", "category": "motivational"},
    {"id": 236, "text": "The best revenge is massive success.", "author": "Frank Sinatra", "category": "motivational"},
    {"id": 237, "text": "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", "author": "Christian D. Larson", "category": "motivational"},
    {"id": 238, "text": "Act as if what you do makes a difference. It does.", "author": "William James", "category": "motivational"},
    {"id": 239, "text": "Everything you can imagine is real.", "author": "Pablo Picasso", "category": "motivational"},
    {"id": 240, "text": "The best time to plant a tree was 20 years ago. The second best time is now.", "author": "Chinese Proverb", "category": "motivational"},
    {"id": 241, "text": "You miss 100% of the shots you don’t take.", "author": "Wayne Gretzky", "category": "motivational"},
    {"id": 242, "text": "Do what you can, with what you have, where you are.", "author": "Theodore Roosevelt", "category": "motivational"},
    {"id": 243, "text": "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", "author": "Christian D. Larson", "category": "motivational"},
    {"id": 244, "text": "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", "author": "Jimmy Dean", "category": "motivational"},
    {"id": 245, "text": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt", "category": "motivational"},
    {"id": 246, "text": "Do not wait to strike till the iron is hot, but make it hot by striking.", "author": "William Butler Yeats", "category": "motivational"},
    {"id": 247, "text": "Keep your face always toward the sunshine—and shadows will fall behind you.", "author": "Walt Whitman", "category": "motivational"},
    {"id": 248, "text": "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "author": "Ralph Waldo Emerson", "category": "motivational"},
    {"id": 249, "text": "It always seems impossible until it’s done.", "author": "Nelson Mandela", "category": "motivational"},
    {"id": 250, "text": "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", "author": "Roy T. Bennett", "category": "motivational"},
    {"id": 251, "text": "Life is either a daring adventure or nothing at all.", "author": "Helen Keller", "category": "motivational"},
    {"id": 252, "text": "You can't cross the sea merely by standing and staring at the water.", "author": "Rabindranath Tagore", "category": "motivational"},
    {"id": 253, "text": "It always seems impossible until it’s done.", "author": "Nelson Mandela", "category": "motivational"},
    {"id": 254, "text": "To live a creative life, we must lose our fear of being wrong.", "author": "Joseph Chilton Pearce", "category": "motivational"},
    {"id": 255, "text": "If you want to achieve greatness stop asking for permission.", "author": "Anonymous", "category": "motivational"},
    {"id": 256, "text": "There are no shortcuts to any place worth going.", "author": "Beverly Sills", "category": "motivational"},
    {"id": 257, "text": "The best way to predict the future is to invent it.", "author": "Alan Kay", "category": "motivational"},
    {"id": 258, "text": "I am not a product of my circumstances. I am a product of my decisions.", "author": "Stephen R. Covey", "category": "motivational"},
    {"id": 259, "text": "Success is the sum of small efforts, repeated day in and day out.", "author": "Robert Collier", "category": "motivational"},
    {"id": 260, "text": "Nothing is impossible, the word itself says ‘I’m possible’!", "author": "Audrey Hepburn", "category": "motivational"},
    {"id": 261, "text": "In the middle of difficulty lies opportunity.", "author": "Albert Einstein", "category": "motivational"},
    {"id": 262, "text": "Start where you are. Use what you have. Do what you can.", "author": "Arthur Ashe", "category": "motivational"},
    {"id": 263, "text": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt", "category": "motivational"},
    {"id": 264, "text": "I find that the harder I work, the more luck I seem to have.", "author": "Thomas Jefferson", "category": "motivational"},
    {"id": 265, "text": "Success usually comes to those who are too busy to be looking for it.", "author": "Henry David Thoreau", "category": "motivational"},
    {"id": 266, "text": "Don’t watch the clock; do what it does. Keep going.", "author": "Sam Levenson", "category": "motivational"},
    {"id": 267, "text": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt", "category": "motivational"},
    {"id": 268, "text": "You don’t have to be great to start, but you have to start to be great.", "author": "Zig Ziglar", "category": "motivational"},
    {"id": 269, "text": "What we think, we become.", "author": "Buddha", "category": "motivational"},
    {"id": 270, "text": "It’s never too late to be what you might have been.", "author": "George Eliot", "category": "motivational"},
    {"id": 271, "text": "The harder you work for something, the greater you’ll feel when you achieve it.", "author": "Anonymous", "category": "motivational"},
    {"id": 272, "text": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett", "category": "motivational"},
    {"id": 273, "text": "Failure will never overtake me if my determination to succeed is strong enough.", "author": "Og Mandino", "category": "motivational"},
    {"id": 274, "text": "You only live once, but if you do it right, once is enough.", "author": "Mae West", "category": "motivational"},
    {"id": 275, "text": "It’s not whether you get knocked down, it’s whether you get up.", "author": "Vince Lombardi", "category": "motivational"},
    {"id": 276, "text": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis", "category": "motivational"},
    {"id": 277, "text": "Nothing is impossible. The word itself says ‘I’m possible!'", "author": "Audrey Hepburn", "category": "motivational"},
    {"id": 278, "text": "The only way to achieve the impossible is to believe it is possible.", "author": "Charles Kingsleigh", "category": "motivational"},
    {"id": 279, "text": "There are no limits to what you can accomplish, except the limits you place on your own thinking.", "author": "Brian Tracy", "category": "motivational"},
    {"id": 280, "text": "Your time is limited, so don’t waste it living someone else’s life.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 281, "text": "The only way to do great work is to love what you do.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 282, "text": "Life isn’t about finding yourself. Life is about creating yourself.", "author": "George Bernard Shaw", "category": "motivational"},
    {"id": 283, "text": "If you can dream it, you can do it.", "author": "Walt Disney", "category": "motivational"},
    {"id": 284, "text": "We may encounter many defeats, but we must not be defeated.", "author": "Maya Angelou", "category": "motivational"},
    {"id": 285, "text": "A person who never made a mistake never tried anything new.", "author": "Albert Einstein", "category": "motivational"},
    {"id": 286, "text": "Everything you can imagine is real.", "author": "Pablo Picasso", "category": "motivational"},
    {"id": 287, "text": "If you don't value your time, neither will others. Stop giving away your time and talents—start charging for it.", "author": "Kim Garst", "category": "motivational"},
    {"id": 288, "text": "The journey of a thousand miles begins with one step.", "author": "Lao Tzu", "category": "motivational"},
    {"id": 289, "text": "In three words I can sum up everything I've learned about life: it goes on.", "author": "Robert Frost", "category": "motivational"},
    {"id": 290, "text": "Live in the sunshine, swim the sea, drink the wild air.", "author": "Ralph Waldo Emerson", "category": "motivational"},
    {"id": 291, "text": "The best way out is always through.", "author": "Robert Frost", "category": "motivational"},
    {"id": 292, "text": "Don’t wait for opportunity. Create it.", "author": "Anonymous", "category": "motivational"},
    {"id": 293, "text": "The road to success and the road to failure are almost exactly the same.", "author": "Colin R. Davis", "category": "motivational"},
    {"id": 294, "text": "You have to be odd to be number one.", "author": "Dr. Seuss", "category": "motivational"},
    {"id": 295, "text": "Life is not about waiting for the storm to pass, but about learning how to dance in the rain.", "author": "Vivian Greene", "category": "motivational"},
    {"id": 296, "text": "The best revenge is massive success.", "author": "Frank Sinatra", "category": "motivational"},
    {"id": 297, "text": "Don’t let yesterday take up too much of today.", "author": "Will Rogers", "category": "motivational"},
    {"id": 298, "text": "We do not remember days, we remember moments.", "author": "Cesare Pavese", "category": "motivational"},
    {"id": 299, "text": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius", "category": "motivational"},
    {"id": 300, "text": "Success is not in what you have, but who you are.", "author": "Bo Bennett", "category": "motivational"},
    {"id": 301, "text": "Act as if what you do makes a difference. It does.", "author": "William James", "category": "motivational"},
    {"id": 302, "text": "Life is what happens when you’re busy making other plans.", "author": "John Lennon", "category": "motivational"},
    {"id": 303, "text": "The best time to plant a tree was 20 years ago. The second best time is now.", "author": "Chinese Proverb", "category": "motivational"},
    {"id": 304, "text": "You are never too old to set another goal or to dream a new dream.", "author": "C.S. Lewis", "category": "motivational"},
    {"id": 305, "text": "Don’t judge each day by the harvest you reap, but by the seeds that you plant.", "author": "Robert Louis Stevenson", "category": "motivational"},
    {"id": 306, "text": "The mind is everything. What you think you become.", "author": "Buddha", "category": "motivational"},
    {"id": 307, "text": "We become what we think about.", "author": "Earl Nightingale", "category": "motivational"},
    {"id": 308, "text": "The greatest glory in living lies not in never falling, but in rising every time we fall.", "author": "Nelson Mandela", "category": "motivational"},
    {"id": 309, "text": "In the end, it’s not the years in your life that count. It’s the life in your years.", "author": "Abraham Lincoln", "category": "motivational"},
    {"id": 310, "text": "Don’t count the days, make the days count.", "author": "Muhammad Ali", "category": "motivational"},
    {"id": 311, "text": "You miss 100% of the shots you don’t take.", "author": "Wayne Gretzky", "category": "motivational"},
    {"id": 312, "text": "Whether you think you can or you think you can’t, you’re right.", "author": "Henry Ford", "category": "motivational"},
    {"id": 313, "text": "I have not failed. I’ve just found 10,000 ways that won’t work.", "author": "Thomas Edison", "category": "motivational"},
    {"id": 314, "text": "Life isn’t about waiting for the storm to pass, it’s about learning to dance in the rain.", "author": "Anonymous", "category": "motivational"},
    {"id": 315, "text": "You only live once, but if you do it right, once is enough.", "author": "Mae West", "category": "motivational"},
    {"id": 316, "text": "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", "author": "Ralph Waldo Emerson", "category": "motivational"},
    {"id": 317, "text": "Don’t cry because it’s over, smile because it happened.", "author": "Dr. Seuss", "category": "motivational"},
    {"id": 318, "text": "Do one thing every day that scares you.", "author": "Eleanor Roosevelt", "category": "motivational"},
    {"id": 319, "text": "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", "author": "Ralph Waldo Emerson", "category": "motivational"},
    {"id": 320, "text": "The only impossible journey is the one you never begin.", "author": "Tony Robbins", "category": "motivational"},
    {"id": 321, "text": "There are no limits to what you can accomplish, except the limits you place on your own thinking.", "author": "Brian Tracy", "category": "motivational"},
    {"id": 322, "text": "Success is not final, failure is not fatal: It is the courage to continue that counts.", "author": "Winston Churchill", "category": "motivational"},
    {"id": 323, "text": "It always seems impossible until it’s done.", "author": "Nelson Mandela", "category": "motivational"},
    {"id": 324, "text": "We may encounter many defeats, but we must not be defeated.", "author": "Maya Angelou", "category": "motivational"},
    {"id": 325, "text": "You are never too old to set another goal or to dream a new dream.", "author": "C.S. Lewis", "category": "motivational"},
    {"id": 326, "text": "Our lives are defined by opportunities, even the ones we miss.", "author": "F. Scott Fitzgerald", "category": "motivational"},
    {"id": 327, "text": "Everything you can imagine is real.", "author": "Pablo Picasso", "category": "motivational"},
    {"id": 328, "text": "The only way to do great work is to love what you do.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 329, "text": "If you can dream it, you can do it.", "author": "Walt Disney", "category": "motivational"},
    {"id": 330, "text": "The best revenge is massive success.", "author": "Frank Sinatra", "category": "motivational"},
    {"id": 331, "text": "In three words I can sum up everything I've learned about life: it goes on.", "author": "Robert Frost", "category": "motivational"},
    {"id": 332, "text": "Life is what happens when you’re busy making other plans.", "author": "John Lennon", "category": "motivational"},
    {"id": 333, "text": "The best way out is always through.", "author": "Robert Frost", "category": "motivational"},
    {"id": 334, "text": "You don’t have to be great to start, but you have to start to be great.", "author": "Zig Ziglar", "category": "motivational"},
    {"id": 335, "text": "What we think, we become.", "author": "Buddha", "category": "motivational"},
    {"id": 336, "text": "It’s never too late to be what you might have been.", "author": "George Eliot", "category": "motivational"},
    {"id": 337, "text": "The harder you work for something, the greater you’ll feel when you achieve it.", "author": "Anonymous", "category": "motivational"},
    {"id": 338, "text": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett", "category": "motivational"},
    {"id": 339, "text": "Failure will never overtake me if my determination to succeed is strong enough.", "author": "Og Mandino", "category": "motivational"},
    {"id": 340, "text": "You only live once, but if you do it right, once is enough.", "author": "Mae West", "category": "motivational"},
    {"id": 341, "text": "It’s not whether you get knocked down, it’s whether you get up.", "author": "Vince Lombardi", "category": "motivational"},
    {"id": 342, "text": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis", "category": "motivational"},
    {"id": 343, "text": "Nothing is impossible. The word itself says ‘I’m possible!'", "author": "Audrey Hepburn", "category": "motivational"},
    {"id": 344, "text": "The only way to achieve the impossible is to believe it is possible.", "author": "Charles Kingsleigh", "category": "motivational"},
    {"id": 345, "text": "There are no limits to what you can accomplish, except the limits you place on your own thinking.", "author": "Brian Tracy", "category": "motivational"},
    {"id": 346, "text": "Your time is limited, so don’t waste it living someone else’s life.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 347, "text": "The only way to do great work is to love what you do.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 348, "text": "Life isn’t about finding yourself. Life is about creating yourself.", "author": "George Bernard Shaw", "category": "motivational"},
    {"id": 349, "text": "If you can dream it, you can do it.", "author": "Walt Disney", "category": "motivational"},
    {"id": 350, "text": "We may encounter many defeats, but we must not be defeated.", "author": "Maya Angelou", "category": "motivational"},
    {"id": 351, "text": "Keep your face always toward the sunshine—and shadows will fall behind you.", "author": "Walt Whitman", "category": "motivational"},
    {"id": 352, "text": "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", "author": "Albert Schweitzer", "category": "motivational"},
    {"id": 353, "text": "Don't watch the clock; do what it does. Keep going.", "author": "Sam Levenson", "category": "motivational"},
    {"id": 354, "text": "Opportunities don't happen, you create them.", "author": "Chris Grosser", "category": "motivational"},
    {"id": 355, "text": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius", "category": "motivational"},
    {"id": 356, "text": "Everything you can imagine is real.", "author": "Pablo Picasso", "category": "motivational"},
    {"id": 357, "text": "The best way to predict the future is to create it.", "author": "Abraham Lincoln", "category": "motivational"},
    {"id": 358, "text": "The journey of a thousand miles begins with one step.", "author": "Lao Tzu", "category": "motivational"},
    {"id": 359, "text": "You miss 100% of the shots you don’t take.", "author": "Wayne Gretzky", "category": "motivational"},
    {"id": 360, "text": "The only way to do great work is to love what you do.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 361, "text": "Don’t count the days, make the days count.", "author": "Muhammad Ali", "category": "motivational"},
    {"id": 362, "text": "Success is the sum of small efforts, repeated day in and day out.", "author": "Robert Collier", "category": "motivational"},
    {"id": 363, "text": "What you get by achieving your goals is not as important as what you become by achieving your goals.", "author": "Zig Ziglar", "category": "motivational"},
    {"id": 364, "text": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt", "category": "motivational"},
    {"id": 365, "text": "The harder you work for something, the greater you’ll feel when you achieve it.", "author": "Anonymous", "category": "motivational"},
    {"id": 366, "text": "Dream big and dare to fail.", "author": "Norman Vaughan", "category": "motivational"},
    {"id": 367, "text": "Don’t be afraid to give up the good to go for the great.", "author": "John D. Rockefeller", "category": "motivational"},
    {"id": 368, "text": "It always seems impossible until it’s done.", "author": "Nelson Mandela", "category": "motivational"},
    {"id": 369, "text": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt", "category": "motivational"},
    {"id": 370, "text": "You don’t have to be great to start, but you have to start to be great.", "author": "Zig Ziglar", "category": "motivational"},
    {"id": 371, "text": "The best way out is always through.", "author": "Robert Frost", "category": "motivational"},
    {"id": 372, "text": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett", "category": "motivational"},
    {"id": 373, "text": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis", "category": "motivational"},
    {"id": 374, "text": "What you do today can improve all your tomorrows.", "author": "Ralph Marston", "category": "motivational"},
    {"id": 375, "text": "The best revenge is massive success.", "author": "Frank Sinatra", "category": "motivational"},
    {"id": 376, "text": "Don’t wait. The time will never be just right.", "author": "Napoleon Hill", "category": "motivational"},
    {"id": 377, "text": "Your time is limited, so don’t waste it living someone else’s life.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 378, "text": "The only way to do great work is to love what you do.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 379, "text": "Life isn’t about finding yourself. Life is about creating yourself.", "author": "George Bernard Shaw", "category": "motivational"},
    {"id": 380, "text": "You can never cross the ocean until you have the courage to lose sight of the shore.", "author": "Christopher Columbus", "category": "motivational"},
    {"id": 381, "text": "To live a creative life, we must lose our fear of being wrong.", "author": "Joseph Chilton Pearce", "category": "motivational"},
    {"id": 382, "text": "If you can dream it, you can do it.", "author": "Walt Disney", "category": "motivational"},
    {"id": 383, "text": "What we think, we become.", "author": "Buddha", "category": "motivational"},
    {"id": 384, "text": "It’s never too late to be what you might have been.", "author": "George Eliot", "category": "motivational"},
    {"id": 385, "text": "The harder you work for something, the greater you’ll feel when you achieve it.", "author": "Anonymous", "category": "motivational"},
    {"id": 386, "text": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett", "category": "motivational"},
    {"id": 387, "text": "Failure will never overtake me if my determination to succeed is strong enough.", "author": "Og Mandino", "category": "motivational"},
    {"id": 388, "text": "You only live once, but if you do it right, once is enough.", "author": "Mae West", "category": "motivational"},
    {"id": 389, "text": "It’s not whether you get knocked down, it’s whether you get up.", "author": "Vince Lombardi", "category": "motivational"},
    {"id": 390, "text": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis", "category": "motivational"},
    {"id": 391, "text": "Nothing is impossible. The word itself says ‘I’m possible!'", "author": "Audrey Hepburn", "category": "motivational"},
    {"id": 392, "text": "The only way to achieve the impossible is to believe it is possible.", "author": "Charles Kingsleigh", "category": "motivational"},
    {"id": 393, "text": "There are no limits to what you can accomplish, except the limits you place on your own thinking.", "author": "Brian Tracy", "category": "motivational"},
    {"id": 394, "text": "Your time is limited, so don’t waste it living someone else’s life.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 395, "text": "The only way to do great work is to love what you do.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 396, "text": "Life isn’t about finding yourself. Life is about creating yourself.", "author": "George Bernard Shaw", "category": "motivational"},
    {"id": 397, "text": "If you can dream it, you can do it.", "author": "Walt Disney", "category": "motivational"},
    {"id": 398, "text": "We may encounter many defeats, but we must not be defeated.", "author": "Maya Angelou", "category": "motivational"},
    {"id": 399, "text": "The only way to do great work is to love what you do.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 400, "text": "Do one thing every day that scares you.", "author": "Eleanor Roosevelt", "category": "motivational"},
    {"id": 401, "text": "Don't wait. The time will never be just right.", "author": "Napoleon Hill", "category": "motivational"},
    {"id": 402, "text": "In the middle of every difficulty lies opportunity.", "author": "Albert Einstein", "category": "motivational"},
    {"id": 403, "text": "Success usually comes to those who are too busy to be looking for it.", "author": "Henry David Thoreau", "category": "motivational"},
    {"id": 404, "text": "I find that the harder I work, the more luck I seem to have.", "author": "Thomas Jefferson", "category": "motivational"},
    {"id": 405, "text": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney", "category": "motivational"},
    {"id": 406, "text": "Your limitation—it’s only your imagination.", "author": "Anonymous", "category": "motivational"},
    {"id": 407, "text": "Push yourself, because no one else is going to do it for you.", "author": "Anonymous", "category": "motivational"},
    {"id": 408, "text": "Great things never come from comfort zones.", "author": "Anonymous", "category": "motivational"},
    {"id": 409, "text": "Dream it. Wish it. Do it.", "author": "Anonymous", "category": "motivational"},
    {"id": 410, "text": "Success doesn’t just find you. You have to go out and get it.", "author": "Anonymous", "category": "motivational"},
    {"id": 411, "text": "The harder you work for something, the greater you’ll feel when you achieve it.", "author": "Anonymous", "category": "motivational"},
    {"id": 412, "text": "Dream it. Believe it. Build it.", "author": "Anonymous", "category": "motivational"},
    {"id": 413, "text": "The key to success is to focus on goals, not obstacles.", "author": "Anonymous", "category": "motivational"},
    {"id": 414, "text": "Success is the sum of small efforts, repeated day in and day out.", "author": "Robert Collier", "category": "motivational"},
    {"id": 415, "text": "Don't stop when you're tired. Stop when you're done.", "author": "Anonymous", "category": "motivational"},
    {"id": 416, "text": "Wake up with determination. Go to bed with satisfaction.", "author": "Anonymous", "category": "motivational"},
    {"id": 417, "text": "Little things make big days.", "author": "Anonymous", "category": "motivational"},
    {"id": 418, "text": "It’s going to be hard, but hard does not mean impossible.", "author": "Anonymous", "category": "motivational"},
    {"id": 419, "text": "Don’t wait for opportunity. Create it.", "author": "Anonymous", "category": "motivational"},
    {"id": 420, "text": "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", "author": "Anonymous", "category": "motivational"},
    {"id": 421, "text": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt", "category": "motivational"},
    {"id": 422, "text": "Everything you’ve ever wanted is on the other side of fear.", "author": "George Addair", "category": "motivational"},
    {"id": 423, "text": "Opportunities don’t happen, you create them.", "author": "Chris Grosser", "category": "motivational"},
    {"id": 424, "text": "Don't be afraid to give up the good to go for the great.", "author": "John D. Rockefeller", "category": "motivational"},
    {"id": 425, "text": "If you can dream it, you can do it.", "author": "Walt Disney", "category": "motivational"},
    {"id": 426, "text": "Everything you can imagine is real.", "author": "Pablo Picasso", "category": "motivational"},
    {"id": 427, "text": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius", "category": "motivational"},
    {"id": 428, "text": "The best way to predict the future is to create it.", "author": "Abraham Lincoln", "category": "motivational"},
    {"id": 429, "text": "The journey of a thousand miles begins with one step.", "author": "Lao Tzu", "category": "motivational"},
    {"id": 430, "text": "You miss 100% of the shots you don’t take.", "author": "Wayne Gretzky", "category": "motivational"},
    {"id": 431, "text": "The only way to do great work is to love what you do.", "author": "Steve Jobs", "category": "motivational"},
    {"id": 432, "text": "Don’t count the days, make the days count.", "author": "Muhammad Ali", "category": "motivational"},
    {"id": 433, "text": "Success is the sum of small efforts, repeated day in and day out.", "author": "Robert Collier", "category": "motivational"},
    {"id": 434, "text": "What you get by achieving your goals is not as important as what you become by achieving your goals.", "author": "Zig Ziglar", "category": "motivational"},
    {"id": 435, "text": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt", "category": "motivational"},
    {"id": 436, "text": "The harder you work for something, the greater you’ll feel when you achieve it.", "author": "Anonymous", "category": "motivational"},
    {"id": 437, "text": "Dream big and dare to fail.", "author": "Norman Vaughan", "category": "motivational"},
    {"id": 438, "text": "Don’t be afraid to give up the good to go for the great.", "author": "John D. Rockefeller", "category": "motivational"},
    {"id": 439, "text": "It always seems impossible until it’s done.", "author": "Nelson Mandela", "category": "motivational"},
    {"id": 440, "text": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt", "category": "motivational"},
    
]


@app.get("/quote/random")
def get_random_quote():
    if not quotes:
        raise HTTPException(status_code=404, detail="No quotes found")
    return random.choice(quotes)

# @app.get("/quote/{category}")
# def get_quote_by_category(category: str):
#     filtered_quotes = [q for q in quotes if q["category"].lower() == category.lower()]
#     if not filtered_quotes:
#         raise HTTPException(status_code=404, detail="No quotes found for this category")
#     return random.choice(filtered_quotes)

# @app.post("/quote/add")
# def add_quote(text: str, author: str, category: str):
#     new_quote = {"id": len(quotes) + 1, "text": text, "author": author, "category": category.lower()}
#     quotes.append(new_quote)
#     return {"message": "Quote added successfully", "quote": new_quote}

# Run the server: uvicorn main:app --reload
